version: '3.2'

services:
  web1:
    container_name: web1
    image: nginx
    environment:
        - VIRTUAL_HOST=m

  web2:
    container_name: web2
    image: nginx
    environment:
        - VIRTUAL_HOST=m

  web3:
    container_name: web3
    image: nginx
    environment:
        - VIRTUAL_HOST=m

  web4:
    container_name: web4
    image: nginx
    environment:
        - VIRTUAL_HOST=m

  nginx-loadbalancer:
    image: jwilder/nginx-proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
